### ISSUE TITLE
setup_radar file

### ISSUE THREAD

**Issue by yinzhaorui3** [ekurtgl/AWR2243-RadarGUI#1]
Hi Ekurt,

I am a student in an internship integrating AWR2243BOOST in ROS. 
I was trying to port mmWave Studio CLI to linux so that I can work with AWR2243 in ROS, until I found your work. It helps me forgetting studying all functions and rewriting them from windows to linux and from .c to .cpp. So thanks a lot!
However, I would like to know how the setup_radar file be generated. If I have understood it correctly, the SPI-communication handles and some functions of mmWaveLink API are compressed in it.
Could you tell me where the setup_radar is generated from?

Thank you and best regards

**Comment by ekurtgl** [comment]
Hi @yinzhaorui3,

That srtup_radar file is equivalent of  mmWave application examples on Windows. For example, you can use C:\ti\mmwave_dfp_02_02_03_01\ti\example\mmWaveLink_SingleChip_Example\mmwavelink_example.exe in Windows to setup the radar. setuo_radar file is generated for Linux from the source files, but has the same functionality with the example applications provided by TI. I hope this helps.

Best,
Emre

**Comment by yinzhaorui3** [comment]
Hi Emre,

thank you for you quick response! 
So you have created a makefile to generate a linux-application of mmwave_example. I think the "/home/emre/Desktop/77ghz/open_radar/open_radar_initiative-new_receive_test/open_radar_initiative-new_receive_test/setup_radar/build" directory was also created through this make file?

Best Regards
Zhaorui Yin

**Comment by yinzhaorui3** [comment]
Hi Emre,

I've found the one for mmwave dfp on linux OS and this is what I am looking for: https://github.com/openradarinitiative/openradar_mmwave_utils/tree/368923048e1c449670cac634dcacc549182537af
Thank you for your publishment in github! This will help me a lot!

Best Regards
Zhaorui Yin
